### PR TITLE
Modularization

### PR DESCRIPTION
**Pull request by tsherif**
@mreinstein can you take a look at this since you know how this modular setup works better than I do? Main things I changed were:
- browserify is integrated into the grunt build setup
- I collapsed index.js and picogl.js into a single file. 

Let me know if anything seems out of place.

### CODE REVIEW

**Comment by mreinstein** [comment]
@tsherif looks good! 👍  The only issue I see is that combining `index.js` and `picogl.js` back together means that every module is back to referencing a global variable. My hope in doing this modularization was to avoid referencing globals. That's why `picogl.js` only had gl constants in it. All of the other modules only seem to reference the gl constants, and isolating them made it easy to just pull them in as another require.

**Comment by tsherif** [comment]
@mreinstein Ah, gotcha, thanks for the review. I'm going to merge this in as is for now, but I'll think about making a separate enums module or something like that, so they can be required separately.

**Comment by mreinstein** [comment]
if you'll accept a follow PR, happy to help with that! 👍

**Comment by tsherif** [comment]
Sure thing, thanks! I'd like to keep the main library file as "picogl.js", so maybe the enums file could be called "constants.js".

Then picogl.js could start with:
```JavaScript
var PicoGL = global.PicoGL = require("./constants");

PicoGL.version = "%%VERSION%%";
//... etc.
```

And other files that want to require it would use: 
```JavaScript
var Constants = require("./constants");

// Use things like Constants.FLOAT, Constants.UNSIGNED_INT, etc.
```

How does that sound?

**Comment by mreinstein** [comment]
> How does that sound?

Sounds good! One suggestion; instead of `constants`, how about `gl_enums` or `gl_constants` ? That way it'd be more specific.

**Comment by tsherif** [comment]
Since not all the constants in there are gl constants, I'd prefer to use "constants".

**Comment by mreinstein** [comment]
I thought they were all gl constants? What else is in there?

**Comment by tsherif** [comment]
Only the loop at the beginning captures GL constants. The rest are lookup tables for information that's useful throughout the system.

**Comment by mreinstein** [comment]
ahhh ok. Thanks for the clarification. :) One thing we could do is have a `src/gl_constants` and a `src/picogl_constants`. There's not really a penalty in terms of performance or bundle size and it cleanly groups constants together. Not a big deal though.

**Comment by mreinstein** [comment]
btw I took `examples/cube.html` in my local copy and modified it to use  `require('picogl.js')`.  Works great!

**Comment by tsherif** [comment]
Keep it as one set of constants for now. I'm thinking I might split them later based on where they're used.

That's cool about the cube example :) Can you show me how it's set up?

**Comment by mreinstein** [comment]
> Can you show me how it's set up?

sure, I'll outline the steps here. If this is still confusing I can send you the complete example.

1 open `examples/cube.html`
2 take all of the code out of the script block that sets up the app, and move it to `examples/cube.js`
3 in `cube.js` at the top add this line:  `var PicoGL = require('picogl.js')`
4 install browserify (you could use webpack as well. I'm familiar with browserify.) 
5 add these lines to you "scripts" block in package.json:

```javascript
"scripts": {
   "build-cube": "browserify ./examples/cube.js -v -o examples/cube-bundle.js --verbose"
},
```
6 add this to the bottom of `examples/cube.js`, before the `</body>` tag: 

```html
<script src="cube-bundle.js"></script>
```

7 from the command line, run `npm run build-cube`. That should cause `cube-bundle.js` to appear in the `examples/` directory

8 open up `cube.html in a browser as per normal

**Comment by tsherif** [comment]
Very cool, thanks!

**Comment by mreinstein** [comment]
thank _you_ for making picogl! I'm really looking forward to taking my existing webgl game and ripping out all the boilerplate gl code in favor of pico and webgl2 goodness. :)

**Pull request merged**
