### PR TITLE
Texture defaults

### LINKED ISSUE #133: Defaults for int texture types
Could add some for INT and UNSIGNED_INT here: https://github.com/tsherif/picogl.js/blob/master/src/constants.js#L666

@habemus-papadum

### PR DESCRIPTION
**Pull request by tsherif**
Closes #133 

@habemus-papadum How does this look? Focusing the texture format API on the sized formats, from which the type and format can be inferred.

### CODE REVIEW

**Comment by habemus-papadum** [comment]
Wow, great! Thanks for this.  One mystery I haven't sorted out is that I think there are some internal formats which do not uniquely determine the Format/Type pair e.g. I think GL.R16F can also have GL.HALF_FLOAT, which apparently has measurable performance implications on mobile.  I don't know the full details and was planning to look at the specs later today and will share any thing I learn.  But thanks!

**Comment by tsherif** [comment]
If you provide a `type` option, it will override the default: https://github.com/tsherif/picogl.js/blob/master/src/texture.js#L96

Format can be uniquely determined by internal format: https://www.khronos.org/registry/OpenGL-Refpages/es3.0/html/glTexImage2D.xhtml

**Comment by habemus-papadum** [comment]
Thanks -- Sorry, I did notice the ability to override type -- what I meant to say is that I just don't fully understand the implications of choosing R16F/HALF_FLOAT vs R16F/FLOAT or  GL_R11F_G11F_B10F/FLOAT vs GL_R11F_G11F_B10F/GL_UNSIGNED_INT_10F_11F_11F_REV -- but that is a question for another place.  Everything here makes sense.

**Comment by tsherif** [comment]
I haven't really used them, but I suppose the main use case is if you're finding memory or bandwidth usage to be bottlenecks, and you don't need full precision. I think I'll actually try this out in some of the examples, e.g. deferred normals and uvs likely don't need 32-bit precision.

**Comment by tsherif** [comment]
@habemus-papadum Some interesting quick and dirty results of changing to 16F textures  (type: FLOAT) in some examples on my Linux machine with a Quadro M1000:
- Deffered: -0.3ms (3ms => 2.7ms)
- OIT: -4.5ms! (8ms => 3.5m)
- SSAO: -2ms (7ms => 5ms)

And it made no additional difference if I changed the type to HALF_FLOAT. So I'm guessing a 16F format in a FLOAT texture will just pack them 2:1?

**Comment by habemus-papadum** [comment]
Pretty cool!  I have heard the situation on mobile can be more dramatic.    You might tweak out more improvement lowering the float precision in the shader.  

I spent some time today reading thru the webgl2 spec trying to better understand the nuances of FORMAT/TYPE/INTERNAL_FORMAT -- I'll write a small summary relevant to  #138 tomorrow or the next.

**Pull request merged**
