### PR TITLE
Int float vbo

### LINKED ISSUE #54: Support for float VertexBuffer with TypedArray other than Float32Array
Currently `App.createVertexBuffer`'s `type` argument is used to decide whether to use `vertexAttribPointer ` or `vertexAttribIPointer` when defining a VertexArray attribute but it is also used to set the data type and the stride of the attribute.

https://github.com/tsherif/picogl.js/blob/master/src/vertex-array.js#L129

This means it is not possible to set a non-integer attribute with a Int8Array, because that would require setting its type to BYTE which would trigger the use of `vertexAttribIPointer`.

Using a Int8Array with `type` set to PicoGL.BYTE, for an attribute defined as a float in the shader triggers `GL ERROR :GL_INVALID_OPERATION : glDrawElements: vertexAttrib function must match shader attrib type`.

And using a Int8Array with type set to PicoGL.FLOAT triggers `GL ERROR :GL_INVALID_OPERATION : glDrawElements: attempt to access out of range vertices in attribute X`.

Decoupling the attribute type and the data type (actual ArrayBufferView type) would allow more flexibility. For example, with voxel-based meshes it is possible to use 75% less memory on normals and UVs by using Int8Array instead of Float32Array. Likewise an SVG logo converted to a flat 3D mesh could use a Int8Array for its normals.

**PS: Thanks for your work on this library, it's great !**

### PR DESCRIPTION
**Pull request by tsherif**
Closes #54.

vertexAttributeBuffer no longer uses vertexAttribIPointer when passed a Integer typed array. Introduces four new VertexArray methods:
- vertexIntegerAttributeBuffer
- vertexNormalizedAttributeBuffer
- instanceIntegerAttributeBuffer
- instanceNormalizedAttributeBuffer

These methods allow the application to explicitly indicate if it wants attributes passed as integers or unorm/snorm.

### CODE REVIEW

**Comment by tsherif** [comment]
@kchapelier, this should resolve your issue.

**Comment by kchapelier** [comment]
Thank you ! I'll check it tomorrow.

Nice to see support for normalized floats too. 👍

**Comment by kchapelier** [comment]
Sorry for the delay, it resolves my issue indeed 👍

**Comment by tsherif** [comment]
@kchapelier  Great! Thanks for letting me know :)

**Pull request merged**
