### PR TITLE
Support for array uniforms

### PR DESCRIPTION
**Pull request by Shimmen**
This PR adds support for array uniforms.

It essentially only adds non-cached array version for all of the uniform types and chooses them when a uniform is of array type when setting up new shader programs.

I also took the liberty of shortening the name you refer to the uniforms from the JavaScript code so that e.g. `uniform float values[10]` is referred to as `values` and not `values[0]`. Personally I think this makes everything much clearer (especially if you're not used to pointers), but if this isn't suitable for the thin abstraction that PicoGL supplies I also understand that.

I haven't tested all of it but I know it works as intended for the `Vec4ArrayUniform` type.

### CODE REVIEW

**Comment by Shimmen** [comment]
This partially solves #16.

**Comment by tsherif** [comment]
@Shimmen Thanks for working on this! The update is definitely required. I clearly didn't account for uniform arrays, since I've never really used them. But I'd like to consider a different approach just because I think that uniform.js is getting too big. What do you think of something like this?

- Add a count property to all uniform types that comes from uniformInfo.size, like your doing now.
- Cache size should for the total number of components (e.g. 4 X count for a vec4 array)
- Use a for loop for the cache check to check all components.
- Int/Float/Unit/Bool 1-component uniforms would have to be update to use an array cache even if they only have one element.  

Then the current versions of the uniform classes would (I think) be able to handle arrays as well.

I wonder... could we take this strategy all the way and just have one (or maybe four) uniform classes that dynamically manage the different sizes...? Anyway, not something to worry about now. That can be considered later.

Also, I would prefer not to strip the "[0]" from the uniform name. My general philosophy has been to keep things relatively close to however WebGL does things (even if it's a bit ugly at times).

**Comment by Shimmen** [comment]
I first considered the approach that you suggest, i.e. having 4 base uniform types (int, uint, float, bool) but the problem is that you can't simplify a `vec3` to 3 floats with the uniform API. It has to be passed in as a vec3, i.e. `uniform3f` or `uniform3fv`. Well actually I couldn't find documentation supporting this claim but I did google my way through and found some people that confirmed it and it makes sense from a data-layout perspective.

So I think that you need at least the types that currently exist. Then the reason for creating *ArrayUniform types for every type is less motivated. Since a uniform array in theory could be very large I thought that caching that much memory would be a waste, so lets create new classes for arrays that doesn't cache. This was just some intuition though and not based on any statistics. If you think caching is worth for arrays I'm all for it. I can make that change quite quickly.

And I'll fix the naming thing, no problem!

**Comment by tsherif** [comment]
Great! I'm thinking yeah, implement the caching for everything for now. We can check later to see at what point the caching overhead outweighs the savings from not making the GL call, and add a bit of logic to disable caching if the number of components is too high.

**Comment by tsherif** [comment]
@Shimmen Just wondering, are still planning to work on this?

**Comment by Shimmen** [comment]
Yes, sorry! I've been away for a few days so haven't been able to do anything. I did look at it some today though.

I was thinking about for the int/uint/float/bool types doing something like:

```JavaScript
PicoGL.FloatUniform = function FloatUniform(gl, handle, count) {
    this.gl = gl;
    this.handle = handle;
    this.count = count;
    this.cache = new Float32Array(count);
};

PicoGL.FloatUniform.prototype.set = function(value) {
    if (this.count == 1 && typeof value === "number" && value !== this.cache[0]) {
        this.gl.uniform1f(this.handle, value);
        this.cache[0] = value;
    } else {
        for (var i = 0; i < value.length; i++) {
            if (this.cache[i] !== value[i]) {
                this.gl.uniform1fv(this.handle, value);
                this.cache.set(value);
            }
        }
    }
};
```

And for the vector and matrix types:

```JavaScript
PicoGL.Vec2Uniform = function Vec2Uniform(gl, handle, count) {
    this.gl = gl;
    this.handle = handle;
    this.count = count;
    this.cache = new Float32Array(2 * count);
};

PicoGL.Vec2Uniform.prototype.set = function(value) {
    var length = Math.floor(value.length / 2);
    for (var i = 0; i < length; i++) {
        if (this.cache[2 * i + 0] !== value[2 * i + 0] ||
            this.cache[2 * i + 1] !== value[2 * i + 1]) {
            this.gl.uniform2fv(this.handle, value);
            this.cache.set(value);
        }
    }
};
```

It's not the most safe approach (e.g. passing in a value that is longer than the cache) but it's simple. The bool types will have to be a bit different too. Not 100% sure on what is best to do with them.

**Comment by tsherif** [comment]
@Shimmen No problem at all. I think this will be a cool update :)

Your approach looks good. A few issues:

First, make sure to pull the gl call outside the loop: 
```JavaScript
var update = false;
for (var i = 0; i < value.length; i++) {
    if (this.cache[i] !== value[i]) {
       update = true;
       break;
    }
}
if (update) {
    this.gl.uniform1fv(this.handle, value);
    this.cache.set(value);
}
```
For the vector uniforms, you don't have to split up the checks for each component:
```JavaScript
PicoGL.Vec2Uniform.prototype.set = function(value) {
    var update = false;
    for (var i = 0, len = value.length; i < len; ++i) {
        if (this.cache[i] !== value[i]) {
            update = true;
            break;
        }
    }
    if (update) {
        this.gl.uniform2fv(this.handle, value);
        this.cache.set(value);
    }
};
```

Also, since these will be called a lot, I think it's worth micro-optimizing the loops:
```JavaScript
for (var i = 0, len = value.length; i < len; ++i) {
```

Actually, this is going back on my earlier suggestion, but maybe just for the single-component uniforms, there should be two classes? E.g. FloatUniform and FloatArrayUniform? I don't love that you have to have that branch in the set() method.

**Comment by Shimmen** [comment]
Yeah, of course! I just wrote it here on GitHub, never actually ran it, so I missed some important stuff like breaking out of the loop... I'll get on it right now.

**Comment by Shimmen** [comment]
I have now made the changes. I did not pull out the gl calls out of the loops, but since there is now only one gl call per "set" function I just make sure to break out of the loop after doing the relevant stuff. I am assuming that's what you intended. Or is there a reason not to have it inside the loop at all?

I'm also still somewhat unsure about how to handle the boolean uniforms in the best way. As a user I would like to be able to set a boolean uniforms as either a number (`0, 1.0, [0.0, 1], ...`) or as a boolean (`false, true, [true, true], ...`). All of these cases aren't properly handled as of now because of the caching and equality checks. I am also unsure of how the WebGL API handles typecasting: what happens if i pass `[true, false]` to `gl.uniform2iv` for a `bvec2`? Will that be taken care of completely by the API and resolve to a `bvec2(true, false)`? I can't seems to find any information in the specification.

**Comment by tsherif** [comment]
@Shimmen This looks great! I see what you mean about the Bool array, because the cache has to be an array of booleans. I'd suggest having a BoolArrayUniform, but not a BoolUniform, since the IntUniform can still handle that case. The BoolArrayUniform would still use uniform1i for the update, but would use an array of bools for the cache, similar to how the BoolVecn classes work [e.g.](https://github.com/tsherif/picogl.js/blob/master/src/uniforms.js#L210). Then in program.js, something like this:

```JavaScript
                case PicoGL.BOOL:
                    UniformClass = elementCount > 1 ? PicoGL.BoolArrayUniform : PicoGL.IntUniform;
                    break;
                case PicoGL.INT:
                //...
```

Passing bools to uniformnv does work, and I believe that's more of a JS spec thing, since it has to do with the way things happen in the Int32Array constructor? I'd have to look a little deeper into the specs to confirm, but I'm comfortable with you doing things in that way.

**Comment by tsherif** [comment]
@Shimmen Here's the relevant section on Int32 conversions from the ECMA spec: http://www.ecma-international.org/ecma-262/6.0/#sec-toint32

**Comment by Shimmen** [comment]
Thanks for the information and help!

It should now work, but as you could imagine there were some level of copy-pasting involved in this, so a proper test of it is probably not a bad idea...

**Comment by tsherif** [comment]
@Shimmen Nice! At first glance, everything looks good, but I'll test a bit tonight and hopefully get this in tonight or tomorrow.

**Comment by Shimmen** [comment]
I also made a little quick and contrived example where I make use of uniform arrays in some different ways. You can check it out [here](https://github.com/Shimmen/picogl.js/blob/uniform-array-example/examples/color-indexed-sphere.html).

**Comment by tsherif** [comment]
@Shimmen Very handy. I'll use that as a basis for my tests. Thanks!

**Pull request merged**
